# Generated by Django 6.1.1 on 2026-10-02 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cnh_numero', models.CharField(max_length=11, unique=True, verbose_name='nº da CNH')),
                ('cnh_categoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='categoria da CNH')),
                ('cnh_validade', models.DateField(verbose_name='validade da CNH')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'motorista',
                'verbose_name_plural': 'motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='CPF / documento')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'passageiro',
                'verbose_name_plural': 'passageiros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome / código')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='distância (km)')),
                ('duracao_minutos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='duração (minutos)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField(verbose_name='ano de fabricação')),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('VAN', 'Van'), ('MICROONIBUS', 'Micro-ônibus'), ('ONIBUS', 'Ônibus'), ('CAMINHAO', 'Caminhão')], max_length=20)),
                ('capacidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidade de passageiros')),
                ('quilometragem', models.PositiveIntegerField(default=0, verbose_name='quilometragem atual')),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_VIAGEM', 'Em viagem'), ('MANUTENCAO', 'Em manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20, verbose_name='situação')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_partida', models.DateTimeField(db_index=True, verbose_name='data e hora de partida')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='AGENDADA', max_length=20)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.motorista')),
                ('passageiros', models.ManyToManyField(blank=True, to='frota.passageiro')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.rota')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'viagem',
                'verbose_name_plural': 'viagens',
                'ordering': ['data_hora_partida'],
            },
        ),
    ]
